Repository SAMMaru5/SAMMaruClient, pull requests merged in 2022-07, with the labels that each got.

#27 feat: 사진 파일 여러 개 등록하기 (#26)
  src/pages/photo/PhotoUpdate.js
  src/pages/photo/PhotoUpdate.scss
Labels: ⚙FEAT, 💻API

#33 [feat] : 로그인 페이지 input place holder 변경 (아이디 => 학번)
  src/pages/login/LoginPage.js
  src/pages/management/BoardManage.js
Labels: 🛠FIX

#35 [FIX] Button 클릭 시 disabled 속성으로 변경
  src/pages/freeBoard/FreeBoardUpdate.js
  src/pages/login/LoginPage.js
  src/pages/modifyUserInfo/CheckPwPage.js
  src/pages/modifyUserInfo/ModifyUserInfoPage.js
  src/pages/notice/NoticeUpdate.js
  src/pages/photo/PhotoUpdate.js
  src/pages/register/RegisterPage.js
Labels: 🛠FIX

#36 [feat] : 회원 권한 변경 페이지 제작 (#29)
  src/pages/management/ManagementPage.js
  src/pages/management/MemberManage.js
  src/pages/management/MemberManage.scss
Labels: ⚙FEAT, 💻API

#37 [feat] : 메인 페이지 디자인 변경
  package-lock.json
  package.json
  public/assets/css/fontawesome-all.min.css
  public/assets/css/images/bracket.svg
  public/assets/css/main.css
  public/assets/js/breakpoints.min.js
  public/assets/js/browser.min.js
  public/assets/js/jquery.dropotron.min.js
  public/assets/js/jquery.min.js
  public/assets/js/main.js
  public/assets/js/util.js
  public/assets/sass/libs/_breakpoints.scss
  public/assets/sass/libs/_functions.scss
  public/assets/sass/libs/_html-grid.scss
  public/assets/sass/libs/_mixins.scss
  public/assets/sass/libs/_vars.scss
  public/assets/sass/libs/_vendor.scss
  public/assets/sass/main.scss
  public/assets/webfonts/fa-brands-400.eot
  public/assets/webfonts/fa-brands-400.svg
  public/assets/webfonts/fa-brands-400.ttf
  public/assets/webfonts/fa-brands-400.woff
  public/assets/webfonts/fa-brands-400.woff2
  public/assets/webfonts/fa-regular-400.eot
  public/assets/webfonts/fa-regular-400.svg
  public/assets/webfonts/fa-regular-400.ttf
  public/assets/webfonts/fa-regular-400.woff
  public/assets/webfonts/fa-regular-400.woff2
  public/assets/webfonts/fa-solid-900.eot
  public/assets/webfonts/fa-solid-900.svg
  public/assets/webfonts/fa-solid-900.ttf
  public/assets/webfonts/fa-solid-900.woff
  public/assets/webfonts/fa-solid-900.woff2
  public/img/banner.jpg
  public/index.html
  src/components/Footer.js
  src/components/Navigation.js
  src/imgs/img1.jpg
  src/imgs/img2.jpg
  src/imgs/img3.jpg
  src/imgs/logo.png
  src/imgs/pic.jpg
  src/imgs/pic05.jpg
  src/imgs/pic06.jpg
  src/imgs/pic07.jpg
  src/imgs/sammaru.png
  src/pages/main/ClubActivities.js
  src/pages/main/ClubIntroduction.js
  src/pages/main/ClubIntroduction.scss
  src/pages/main/MainPage.js
Labels: 💄UI/UX, ⚙FEAT

#42 [feat]: 비밀번호 찾기 페이지 제작 (#34)
  src/pages/findUser/FindUserPage.js
  src/pages/findUser/FindUserPage.scss
Labels: ⚙FEAT, 💻API

#43 [fix]: 메인페이지에 게시판 출력 (#41)
  src/pages/main/Board.js
  src/pages/main/Board.scss
  src/pages/main/MainPage.js
Labels: 🛠FIX

#45 [feat]: 공지사항 페이지 디자인 변경(#44)
  public/img/testPicture.PNG
  src/imgs/banner/awards.jpg
  src/imgs/banner/introduce.jpg
  src/imgs/banner/member1.jpg
  src/imgs/banner/member10.jpg
  src/imgs/banner/member2.jpg
  src/imgs/banner/member3.jpg
  src/imgs/banner/member4.jpg
  src/imgs/banner/member5.jpg
  src/imgs/banner/member6.jpg
  src/imgs/banner/member7.jpg
  src/imgs/banner/member8.jpg
  src/imgs/banner/member9.jpg
  src/imgs/banner/notice.jpg
  src/imgs/banner/photo.jpg
  src/imgs/pic05.jpg
  src/imgs/pic06.jpg
  src/imgs/pic07.jpg
  src/pages/notice/NoticePage.js
  src/pages/notice/NoticePage.scss
Labels: 💄UI/UX, ⚙FEAT

#46 [feat] 동아리 수상 경력 페이지 추가 (#39)
  public/img/awardBanner.jpg
  src/Router.js
  src/components/Navigation.js
  src/pages/about/AwardsPage.js
  src/pages/about/AwardsPage.scss
Labels: 💄UI/UX, ⚙FEAT

#48 [feat]: 수상경력 페이지 디자인 변경 (#47)
  public/KakaoTalk_Moim_3j5Aj3GPJCSf5xatggd2eVZXl3R62m.jpg
  public/free-animated-icon-checklist-6416398.gif
  public/img/awardBanner.jpg
  public/noticeThumbNail.png
  src/pages/about/AwardsPage.js
  src/pages/about/AwardsPage.scss
Labels: 💄UI/UX, ⚙FEAT

#50 [feat]: 동아리 소개 페이지 추가 (#38)
  src/Router.js
  src/components/Navigation.js
  src/imgs/icon/iconIntro1.png
  src/imgs/icon/iconIntro2.png
  src/imgs/icon/iconIntro3.png
  src/imgs/img.png
  src/pages/about/AwardsPage.scss
  src/pages/about/IntroClubPage.js
  src/pages/about/IntroClubPage.scss
Labels: 💄UI/UX, ⚙FEAT

#51 [feat]: 사진첩 페이지 디자인 변경 (#49)
  src/pages/photo/PhotoDetail.js
  src/pages/photo/PhotoDetail.scss
  src/pages/photo/PhotoList.js
  src/pages/photo/PhotoList.scss
  src/pages/photo/PhotoPage.js
Labels: 💄UI/UX, ⚙FEAT

#55 [fix]: 회원가입 정규식 수정, 백앤드 정규식으로 통일 (#40)
  src/pages/register/RegisterPage.js
Labels: 🛠FIX

#57 [feat]: 자유게시판 페이지 제작 (#52)
  src/components/Navigation.js
  src/imgs/banner/free.jpg
  src/pages/freeBoard/FreeBoardDetail.scss
  src/pages/freeBoard/FreeBoardDetailPage.js
  src/pages/freeBoard/FreeBoardPage.js
Labels: 💄UI/UX, ⚙FEAT

#59 [fix]: 공지사항 디테일 페이지 제목 제대로 뜨도록 수정, 여백 및 크기 수정, 코드 오타 수정
  src/pages/notice/NoticeDetail.scss
  src/pages/notice/NoticeDetailPage.js
  src/pages/notice/NoticePage.js
Labels: 🛠FIX

#62 [fix]: Warning 제거 (#60)
  package.json
  src/components/Navigation.js
  src/pages/about/AwardsPage.js
  src/pages/findUser/FindUserPage.js
  src/pages/freeBoard/FreeBoardDetailPage.js
  src/pages/freeBoard/FreeBoardPage.js
  src/pages/freeBoard/FreeBoardUpdate.js
  src/pages/main/Board.js
  src/pages/main/ClubActivities.js
  src/pages/main/ClubIntroduction.js
  src/pages/main/MainPage.js
  src/pages/management/ScheduleManage.js
  src/pages/notice/NoticeDetailPage.js
  src/pages/notice/NoticePage.js
  src/pages/notice/NoticeUpdate.js
  src/pages/photo/PhotoDetail.js
  src/pages/photo/PhotoList.js
  src/pages/photo/PhotoPage.js
  src/pages/photo/PhotoUpdate.js
Labels: 🛠FIX

#64 [feat]: 족보게시판 페이지 제작 (#63)
  src/Router.js
  src/components/Navigation.js
  src/imgs/banner/exam.jpg
  src/imgs/banner/project.jpg
  src/pages/exam/ExamDetailPage.js
  src/pages/exam/ExamPage.js
  src/pages/exam/ExamUpdate.js
Labels: 💄UI/UX, ⚙FEAT
