Repository SAMMaru5/SAMMaruClient, pull requests merged in 2022-12, with the labels that each got.

#211 [bug]: 게시글 내용 확인 시 이스케이프 시퀀스 처리가 되지 않았던 문제 수정 (#210)
  src/pages/exam/ExamDetailPage.js
  src/pages/freeBoard/FreeBoardDetailPage.js
  src/pages/notice/NoticeDetailPage.js
  src/pages/photo/PhotoDetail.js
  src/pages/report/ReportDetailPage.js
  src/pages/seminar/SeminarDetailPage.js
  src/pages/subProject/ProjectDetailPage.js
Labels: 🐛BUG

#216 [fix]: 동아리 수상 정보 상장 관련 컴포넌트 제거 (#215)
  src/pages/main/ClubAwards.js
  src/pages/main/ClubAwards.scss
  src/pages/main/MainPage.js
Labels: 💄UI/UX, 🛠FIX

#218 [feat]: 비회원 유저의 게시판 접근 시 내부 게시글 열람 및 접근 제한 기능 추가 (#217)
  src/Router.js
  src/hooks/useAuth.js
  src/pages/exam/ExamPage.js
  src/pages/freeBoard/FreeBoardPage.js
  src/pages/notice/NoticePage.js
  src/pages/photo/PhotoList.js
  src/pages/report/ReportPage.js
  src/pages/seminar/SeminarPage.js
  src/pages/subProject/ProjectPage.js
Labels: ⚙FEAT

#220 [feat]: 관리자 페이지의 회원 관리 탭 내부 테이블 내에 (회원 추방 기능) 추가 (#219)
  src/pages/management/MemberManage.js
  src/pages/management/MemberManage.scss
Labels: 💄UI/UX, ⚙FEAT

#222 [fix]: WELCOME TO SAMMARU 클릭 시 '동아리 소개' 페이지로 이동되도록 기능 수정 (#221)
  src/pages/main/MainPage.js
Labels: 🛠FIX

#224 [fix]: 메인페이지 내 (회원가입/로그인) 및 (LoginPage 컴포넌트) UI 요소 디자인 변경 (#223)
  src/components/Navigation.js
  src/components/Navigation.scss
  src/pages/login/LoginPage.js
  src/pages/login/LoginPage.scss
Labels: 💄UI/UX, 🛠FIX

#226 [fix]: 회원 관리 테이블 내 추방 버튼 클릭 시 나타나는 문구 아이콘 변경 (#225)
  src/pages/management/MemberManage.js
Labels: 💄UI/UX, 🛠FIX

#228 [fix]: 캘린더 기능 관련 컴포넌트 일괄 제거 (#227)
  public/assets/css/main.css
  src/pages/main/MainPage.js
  src/pages/main/Schedule.js
  src/pages/main/Schedule.scss
  src/pages/main/ScheduleDetaile.js
  src/pages/main/ScheduleDetaile.scss
  src/pages/management/ManagementPage.js
  src/pages/management/ScheduleManage.js
Labels: 💄UI/UX, 🛠FIX

#230 [fix]: 사용자 인증 관련 에러 수정 (#229)
  package-lock.json
  src/components/Navigation.js
  src/hooks/useAuth.js
  src/hooks/useFetch.js
  src/pages/login/LoginPage.js
  src/pages/main/ClubIntroduction.js
  src/pages/main/MainPage.js
  src/utils/api.js
  yarn.lock
Labels: 💄UI/UX, 🛠FIX

#235 [fix]: 자동 로그인 요소 제거 (#234)
  src/pages/login/LoginPage.js
Labels: 💄UI/UX, 🛠FIX

#232 [fix]: 메인페이지 내 공지사항 테이블 컴포넌트 재 배치 (#231)
  src/pages/main/Board.js
  src/pages/main/MainPage.js
Labels: 💄UI/UX, 🛠FIX

#237 [bug]: 댓글 있는 게시판 호출 에러 해결 (#236)
  src/components/Comment.js
Labels: 🐛BUG

#238 [feat]: 게시글 검색 기능 추가 및 스타일 수정 (#201)
  public/assets/css/main.css
  src/hooks/boardServices.js
  src/pages/exam/ExamPage.js
  src/pages/freeBoard/FreeBoardPage.js
  src/pages/notice/NoticePage.js
  src/pages/report/ReportPage.js
  src/pages/seminar/SeminarPage.js
  src/pages/subProject/ProjectPage.js
Labels: 💄UI/UX, ⚙FEAT, 💻API

#241 [fix]: 로그인 페이지 스타일 수정 (#240)
  public/assets/css/main.css
  src/components/Footer.js
  src/pages/login/LoginPage.js
  src/pages/login/LoginPage.scss
Labels: 💄UI/UX, 🛠FIX

#242 [fix]: 게시글 내 첨부파일 요소 디자인 변경 (#203)
  src/components/Footer.js
  src/components/UploadedFilesInArticle.js
  src/pages/exam/ExamDetail.scss
  src/pages/exam/ExamDetailPage.js
  src/pages/exam/ExamUpdate.js
  src/pages/freeBoard/FreeBoardDetail.scss
  src/pages/freeBoard/FreeBoardDetailPage.js
  src/pages/freeBoard/FreeBoardUpdate.js
  src/pages/notice/NoticeDetail.scss
  src/pages/notice/NoticeDetailPage.js
  src/pages/notice/NoticeUpdate.js
  src/pages/report/ReportDetail.scss
  src/pages/report/ReportDetailPage.js
  src/pages/report/ReportUpdate.js
  src/pages/seminar/SeminarDetail.scss
  src/pages/seminar/SeminarDetailPage.js
  src/pages/seminar/SeminarUpdate.js
  src/pages/subProject/ProjectDetail.scss
  src/pages/subProject/ProjectDetailPage.js
  src/pages/subProject/ProjectUpdate.js
Labels: 💄UI/UX, 🛠FIX

#244 [bug]: 게시글 등록 중 파일 첨부 시 발생하는 warning 제거 (#243)
  src/pages/exam/ExamUpdate.js
  src/pages/freeBoard/FreeBoardUpdate.js
  src/pages/notice/NoticeUpdate.js
  src/pages/report/ReportUpdate.js
  src/pages/seminar/SeminarUpdate.js
  src/pages/subProject/ProjectUpdate.js
Labels: 🐛BUG

#246 [refactor]: 자바스크립트 컴포넌트 파일 확장자 jsx로 일괄 변경 (#245)
  src/Router.jsx
  src/components/Comment.jsx
  src/components/Footer.jsx
  src/components/Navigation.jsx
  src/components/UploadedFilesInArticle.jsx
  src/pages/about/AwardsPage.jsx
  src/pages/exam/ExamDetailPage.jsx
  src/pages/exam/ExamPage.jsx
  src/pages/exam/ExamUpdate.jsx
  src/pages/findUser/FindUserPage.jsx
  src/pages/freeBoard/FreeBoardDetailPage.jsx
  src/pages/freeBoard/FreeBoardPage.jsx
  src/pages/freeBoard/FreeBoardUpdate.jsx
  src/pages/login/LoginPage.jsx
  src/pages/main/Activity.jsx
  src/pages/main/Board.jsx
  src/pages/main/ClubActivities.jsx
  src/pages/main/ClubIntroduction.jsx
  src/pages/main/MainPage.jsx
  src/pages/management/BoardManage.jsx
  src/pages/management/ManagementPage.jsx
  src/pages/management/MemberManage.jsx
  src/pages/modifyUserInfo/CheckPwPage.jsx
  src/pages/modifyUserInfo/ModifyUserInfoPage.jsx
  src/pages/notFound/NotFound.jsx
  src/pages/notice/NoticeDetailPage.jsx
  src/pages/notice/NoticePage.jsx
  src/pages/notice/NoticeUpdate.jsx
  src/pages/photo/PhotoDetail.jsx
  src/pages/photo/PhotoList.jsx
  src/pages/photo/PhotoPage.jsx
  src/pages/photo/PhotoUpdate.jsx
  src/pages/register/AgreePage.jsx
  src/pages/register/RegisterPage.jsx
  src/pages/report/ReportDetailPage.jsx
  src/pages/report/ReportPage.jsx
  src/pages/report/ReportUpdate.jsx
  src/pages/seminar/SeminarDetailPage.jsx
  src/pages/seminar/SeminarPage.jsx
  src/pages/seminar/SeminarUpdate.jsx
  src/pages/subProject/ProjectDetailPage.jsx
  src/pages/subProject/ProjectPage.jsx
  src/pages/subProject/ProjectUpdate.jsx
Labels: REFACTOR

#248 [fix]: 게시글 댓글 '수정 & 삭제' 기능 사용의 대상 설정 로직 수정 (#247)
  src/components/Comment.jsx
Labels: 🛠FIX
