Repository SAMMaru5/SAMMaruClient, pull requests merged in 2022-10, with the labels that each got.

#181 [refactor]: Accesstoken 만료 확인 후 토큰 제거 기능 모듈화 및 회원검색 오류 제거 (#179)
  src/components/Comment.js
  src/hooks/useAuth.js
  src/pages/exam/ExamUpdate.js
  src/pages/freeBoard/FreeBoardUpdate.js
  src/pages/management/BoardManage.js
  src/pages/management/MemberManage.js
  src/pages/management/ScheduleManage.js
  src/pages/modifyUserInfo/CheckPwPage.js
  src/pages/modifyUserInfo/ModifyUserInfoPage.js
  src/pages/notice/NoticeUpdate.js
  src/pages/photo/PhotoUpdate.js
  src/pages/report/ReportUpdate.js
  src/pages/seminar/SeminarUpdate.js
  src/pages/subProject/ProjectUpdate.js
Labels: 🐛BUG, 💄UI/UX, 🛠FIX

#183 [feat]: 게시글 삭제 기능 추가 (#182)
  src/components/Comment.js
  src/hooks/usePostServices.js
  src/pages/exam/ExamDetailPage.js
  src/pages/freeBoard/FreeBoardDetailPage.js
  src/pages/notice/NoticeDetailPage.js
  src/pages/photo/PhotoDetail.js
  src/pages/report/ReportDetailPage.js
  src/pages/seminar/SeminarDetailPage.js
  src/pages/subProject/ProjectDetailPage.js
Labels: 💄UI/UX, ⚙FEAT, 💻API

#185 [fix]: 존재하지 않는 이메일로 임시 비밀번호 생성 API 사용 시 발생하는 에러에 대한 안내 문구 추가 (#184)
  src/pages/findUser/FindUserPage.js
Labels: 🛠FIX

#187 [fix]: 비회원 유저의 족보 게시판 내 게시글 열람 차단 조건식 추가 (#186)
  src/pages/exam/ExamPage.js
Labels: 🛠FIX

#190 [fix]: 비회원 족보 게시판 접근 차단 (#189)
  src/Router.js
  src/components/Navigation.js
  src/pages/exam/ExamPage.js
Labels: 🛠FIX

#193 [fix]: 첨부파일 여러 개 추가 가능하도록 수정
  src/components/Comment.scss
  src/pages/exam/ExamDetailPage.js
  src/pages/exam/ExamUpdate.js
  src/pages/freeBoard/FreeBoardDetailPage.js
  src/pages/freeBoard/FreeBoardUpdate.js
  src/pages/notice/NoticeDetailPage.js
  src/pages/notice/NoticeUpdate.js
  src/pages/report/ReportDetailPage.js
  src/pages/report/ReportUpdate.js
  src/pages/seminar/SeminarDetailPage.js
  src/pages/seminar/SeminarUpdate.js
  src/pages/subProject/ProjectDetailPage.js
  src/pages/subProject/ProjectUpdate.js
Labels: ⚙FEAT, 🛠FIX
