Repository SAMMaru5/SAMMaruClient, pull requests merged in 2022-08, with the labels that each got.

#66 [feat]: 사진첩 상세페이지 권한 확인 및 사용자에게 사진 보여주는 기능 (#18)
  src/hooks/useAuth.js
  src/pages/photo/PhotoDetail.js
  src/pages/photo/PhotoList.js
Labels: ⚙FEAT, 💻API

#69 [feat]: 활동 보고서 페이지 제작 (#68)
  src/Router.js
  src/components/Navigation.js
  src/imgs/banner/report.jpg
  src/pages/report/ReportDetail.scss
  src/pages/report/ReportDetailPage.js
  src/pages/report/ReportPage.js
  src/pages/report/ReportUpdate.js
Labels: 💄UI/UX, ⚙FEAT

#67 [feat]: 소규모 프로젝트 페이지 제작 (#65)
  src/Router.js
  src/components/Navigation.js
  src/pages/subProject/ProjectDetailPage.js
  src/pages/subProject/ProjectPage.js
  src/pages/subProject/ProjectUpdate.js
Labels: 💄UI/UX, ⚙FEAT

#72 [fix]: main.css에 의해 발생한 css 문제 해결 (#71)
  public/index.html
  src/pages/login/LoginPage.scss
  src/pages/management/MemberManage.js
  src/pages/modifyUserInfo/CheckPwPage.scss
  src/pages/modifyUserInfo/ModifyUserInfoPage.js
  src/pages/register/AgreePage.js
  src/pages/register/AgreePage.scss
  src/pages/register/RegisterPage.js
  src/pages/register/RegisterPage.scss
Labels: 💄UI/UX, 🛠FIX

#74 [feat]: 게시판에서 등록한 파일 다운로드 기능 (#73)
  src/pages/exam/ExamDetailPage.js
  src/pages/freeBoard/FreeBoardDetail.scss
  src/pages/freeBoard/FreeBoardDetailPage.js
  src/pages/notice/NoticeDetail.scss
  src/pages/notice/NoticeDetailPage.js
  src/pages/report/ReportDetail.scss
  src/pages/report/ReportDetailPage.js
  src/pages/subProject/ProjectDetailPage.js
Labels: ⚙FEAT, 💻API

#76 [fix]: 홈 화면 사용하지 않은 요소 수정 (#75)
  public/assets/css/main.css
  src/components/Navigation.js
  src/pages/main/ClubActivities.js
  src/pages/main/ClubActivities.scss
  src/pages/main/ClubAwards.js
  src/pages/main/ClubIntroduction.js
  src/pages/main/MainPage.js
Labels: 💄UI/UX, 🛠FIX

#80 [fix]: Navbar CSS 수정 (#79)
  src/components/Navigation.js
  src/components/Navigation.scss
Labels: 💄UI/UX, 🛠FIX

#78 [feat]: 특강자료 페이지 제작 (#77)
  src/Router.js
  src/components/Navigation.js
  src/imgs/banner/seminar.jpg
  src/pages/seminar/SeminarDetail.scss
  src/pages/seminar/SeminarDetailPage.js
  src/pages/seminar/SeminarPage.js
  src/pages/seminar/SeminarUpdate.js
Labels: 💄UI/UX, ⚙FEAT

#83 [fix]: 샘마루 회원 기수페이지 url 변경 (#81)
  src/Router.js
  src/components/Navigation.js
Labels: 🛠FIX

#84 [bug]: 네비게이션바 css 깨짐 현상 해결 (#82)
  public/assets/js/browser.min.js
  public/index.html
Labels: 🐛BUG

#86 [feat]: 사진첩 페이지 디자인 (#85)
  src/pages/photo/PhotoDetail.js
  src/pages/photo/PhotoDetail.scss
  src/pages/photo/PhotoList.js
  src/pages/photo/PhotoList.scss
  src/pages/photo/PhotoPage.js
  src/pages/photo/PhotoUpdate.js
  src/pages/photo/PhotoUpdate.scss
Labels: 💄UI/UX, ⚙FEAT

#92 [fix]: 메인페이지 Warning(경고) 제거 (#91)
  src/components/Navigation.js
  src/pages/main/MainPage.js
Labels: 🛠FIX

#90 [fix]: 회원가입 페이지 CSS 수정 (#89)
  src/pages/register/RegisterPage.scss
Labels: 💄UI/UX, 🛠FIX

#88 [fix]: 공지사항 작성 페이지 ui 통일 (#87)
  package-lock.json
  package.json
  src/pages/notice/NoticePage.js
  src/pages/notice/NoticeUpdate.js
  src/pages/notice/NoticeUpdate.scss
Labels: 🛠FIX

#98 [feat]: 관리자 페이지 접근 권한 확인 (#94)
  src/hooks/useAuth.js
  src/pages/management/ManagementPage.js
Labels: ⚙FEAT, 💻API

#99 [fix]: 관리자 페이지 회원 관리 기능 시스템 이름으로 검색 (#95)
  src/pages/management/MemberManage.js
Labels: 🛠FIX, 💻API

#97 [fix]: API 변경 (#96)
  src/components/Navigation.js
  src/hooks/useAuth.js
Labels: 🛠FIX, 💻API
