Repository SAMMaru5/SAMMaruClient, pull requests merged in 2022-09, with the labels that each got.

#103 [fix]: 사진첩 페이지 반응형 기능 코드의 개선 (#102)
  src/pages/photo/PhotoList.js
  src/pages/photo/PhotoList.scss
Labels: 💄UI/UX, 🛠FIX

#105 [feat]: (게시글 작성) 컴포넌트 내 "작성취소" 버튼 기능 활성화 (#104)
  src/pages/exam/ExamUpdate.js
  src/pages/freeBoard/FreeBoardUpdate.js
  src/pages/notice/NoticeUpdate.js
  src/pages/report/ReportUpdate.js
  src/pages/seminar/SeminarUpdate.js
  src/pages/subProject/ProjectUpdate.js
Labels: ⚙FEAT

#113 [fix]: BASE_URL 주소 감춤 (#112)
  .gitignore
  src/hooks/app-config.js
Labels: 🛠FIX

#109 [fix]: 게시글 디테일 컴포넌트 내 첨부파일 요소 디자인 수정 (#108)
  src/pages/exam/ExamDetailPage.js
  src/pages/freeBoard/FreeBoardDetailPage.js
  src/pages/notice/NoticeDetailPage.js
  src/pages/report/ReportDetailPage.js
  src/pages/seminar/SeminarDetailPage.js
  src/pages/subProject/ProjectDetailPage.js
Labels: 💄UI/UX, 🛠FIX

#115 [feat]: 게시판 전체 Pagination 기능 추가 (#114)
  src/pages/exam/ExamPage.js
  src/pages/freeBoard/FreeBoardPage.js
  src/pages/freeBoard/FreeBoardPage.scss
  src/pages/notice/NoticePage.js
  src/pages/notice/NoticePage.scss
  src/pages/report/ReportPage.js
  src/pages/seminar/SeminarPage.js
  src/pages/subProject/ProjectPage.js
Labels: ⚙FEAT

#119 [bug]: 로그인 에서 발생하는 에러 해결 (#118)
  src/hooks/useAuth.js
Labels: 🐛BUG, 🛠FIX, 💻API

#121 [fix]: refresh token 제거에 따라 update 파일에 대한 코드 수정
  src/pages/exam/ExamUpdate.js
  src/pages/freeBoard/FreeBoardUpdate.js
  src/pages/notice/NoticeUpdate.js
  src/pages/photo/PhotoUpdate.js
  src/pages/report/ReportUpdate.js
  src/pages/seminar/SeminarUpdate.js
  src/pages/subProject/ProjectUpdate.js
Labels: 🛠FIX

#123 [fix]: Pagination 기능에 대한 잘못된 API 호출문 수정 (#122)
  src/pages/exam/ExamPage.js
  src/pages/freeBoard/FreeBoardPage.js
  src/pages/notice/NoticePage.js
  src/pages/photo/PhotoList.js
  src/pages/report/ReportPage.js
  src/pages/seminar/SeminarPage.js
  src/pages/subProject/ProjectPage.js
Labels: 🛠FIX

#130 [bug]: Pagination 버그 수정 (#129)
  src/pages/exam/ExamPage.js
  src/pages/freeBoard/FreeBoardPage.js
  src/pages/notice/NoticePage.js
  src/pages/report/ReportPage.js
  src/pages/seminar/SeminarPage.js
  src/pages/subProject/ProjectPage.js
Labels: 🐛BUG, 🛠FIX

#132 [fix]: Navigation 컴포넌트 내 refreshToken 사용 코드 제거 (#131)
  src/components/Navigation.js
Labels: 🛠FIX

#134 [bug]: 특정 게시판 내 게시글 정보 조회 시 발생하는 버그 제거 (#133)
  src/pages/photo/PhotoList.js
  src/pages/report/ReportPage.js
  src/pages/seminar/SeminarPage.js
  src/pages/subProject/ProjectPage.js
Labels: 🐛BUG

#135 [fix]: 컴포넌트 별로 유저의 권한에 알맞게 접근 또는 차단되도록 수정 (#128)
  src/hooks/useAuth.js
  src/pages/exam/ExamPage.js
  src/pages/exam/ExamUpdate.js
  src/pages/freeBoard/FreeBoardPage.js
  src/pages/freeBoard/FreeBoardUpdate.js
  src/pages/main/Board.js
  src/pages/management/ManagementPage.js
  src/pages/modifyUserInfo/CheckPwPage.js
  src/pages/notice/NoticePage.js
  src/pages/notice/NoticeUpdate.js
  src/pages/photo/PhotoList.js
  src/pages/photo/PhotoPage.js
  src/pages/photo/PhotoUpdate.js
  src/pages/report/ReportPage.js
  src/pages/report/ReportUpdate.js
  src/pages/seminar/SeminarPage.js
  src/pages/seminar/SeminarUpdate.js
  src/pages/subProject/ProjectPage.js
  src/pages/subProject/ProjectUpdate.js
Labels: 🛠FIX

#137 [feat]: 사진첩 컴포넌트 내 Pagination 기능 추가 (#136)
  src/pages/photo/PhotoList.js
  src/pages/photo/PhotoList.scss
Labels: ⚙FEAT

#139 [bug]: 사진첩 게시판 컴포넌트 내 문법적 오류 및 중복 권한 확인 요청 라인의 제거 (#138)
  src/pages/freeBoard/FreeBoardPage.js
  src/pages/main/Board.js
  src/pages/notice/NoticePage.js
  src/pages/photo/PhotoList.js
Labels: 🐛BUG

#146 [bug]: 게시글 내 "작성취소" 버튼 기능 및 Pagination API 호출문 에러 수정 (#145)
  src/hooks/boardServices.js
  src/pages/exam/ExamPage.js
  src/pages/exam/ExamUpdate.js
  src/pages/freeBoard/FreeBoardPage.js
  src/pages/freeBoard/FreeBoardUpdate.js
  src/pages/notice/NoticePage.js
  src/pages/notice/NoticeUpdate.js
  src/pages/photo/PhotoList.js
  src/pages/photo/PhotoUpdate.js
  src/pages/report/ReportPage.js
  src/pages/report/ReportUpdate.js
  src/pages/seminar/SeminarPage.js
  src/pages/seminar/SeminarUpdate.js
  src/pages/subProject/ProjectPage.js
  src/pages/subProject/ProjectUpdate.js
Labels: 🐛BUG, ⚙FEAT

#149 [bug]: 자유게시판 컴포넌트 내 잘못된 값으로 요청한 모듈 함수 호출 인수 수정 (#148)
  src/pages/freeBoard/FreeBoardPage.js
Labels: 🐛BUG

#152 [fix]: response 응답 여부 확인용 불필요 console.log 함수 일괄 주석 처리 및 제거 (#151)
  src/pages/exam/ExamUpdate.js
  src/pages/freeBoard/FreeBoardPage.js
  src/pages/freeBoard/FreeBoardUpdate.js
  src/pages/login/LoginPage.js
  src/pages/main/Board.js
  src/pages/main/Schedule.js
  src/pages/management/ScheduleManage.js
  src/pages/notice/NoticeUpdate.js
  src/pages/photo/PhotoUpdate.js
  src/pages/report/ReportUpdate.js
  src/pages/seminar/SeminarUpdate.js
  src/pages/subProject/ProjectUpdate.js
  src/utils/api.js
Labels: 🛠FIX

#157 [bug]: 메인 페이지 내 공지사항 리스트가 출력되지 않던 버그 수정 (#156)
  src/components/Navigation.js
  src/pages/main/Board.js
Labels: 🐛BUG

#158 [fix]: 컴포넌트 별로 유저의 권한에 알맞게 접근 및 차단이 가능하도록 수정 (#153)
  src/Router.js
  src/pages/exam/ExamPage.js
  src/pages/login/LoginPage.js
  src/pages/management/ManagementPage.js
  src/pages/notice/NoticePage.js
Labels: 🐛BUG

#160 [bug]: 사진첩 게시판 내 Pagination 버그 수정 (#159)
  src/pages/photo/PhotoList.js
Labels: 🐛BUG

#163 [bug]: 게시판 생성 API 호출문 올바른 형식으로 수정 (#162)
  src/pages/management/BoardManage.js
Labels: 🐛BUG

#167 [feat]: NotFound 페이지 추가 (#166)
  src/Router.js
  src/pages/notFound/NotFound.js
  src/pages/notFound/NotFound.scss
Labels: 💄UI/UX, ⚙FEAT

#169 [bug]: 로그아웃 버그 수정 (#168)
  src/components/Navigation.js
  src/hooks/useAuth.js
Labels: 🐛BUG

#171 [bug]: 토큰 유효 시간 만료 후 API 호출 시 발생하는 버그 제거 및 특정 컴포넌트 접근 시 권한 별로 알맞게 차단되도록 코드 수정 (#170)
  src/components/Navigation.js
  src/pages/exam/ExamUpdate.js
  src/pages/freeBoard/FreeBoardUpdate.js
  src/pages/management/BoardManage.js
  src/pages/management/MemberManage.js
  src/pages/management/ScheduleManage.js
  src/pages/notice/NoticePage.js
  src/pages/notice/NoticeUpdate.js
  src/pages/photo/PhotoUpdate.js
  src/pages/report/ReportUpdate.js
  src/pages/seminar/SeminarUpdate.js
  src/pages/subProject/ProjectUpdate.js
Labels: 🐛BUG

#176 [feat]: 게시판 댓글 기능 추가 (#155)
  src/components/Comment.js
  src/components/Comment.scss
  src/pages/exam/ExamDetailPage.js
  src/pages/freeBoard/FreeBoardDetailPage.js
  src/pages/notice/NoticeDetailPage.js
  src/pages/photo/PhotoDetail.js
  src/pages/photo/PhotoDetail.scss
  src/pages/report/ReportDetailPage.js
  src/pages/seminar/SeminarDetailPage.js
  src/pages/subProject/ProjectDetailPage.js
Labels: ⚙FEAT, 💻API

#173 [bug]: 정보수정 컴포넌트 버그 제거 (#172)
  src/pages/modifyUserInfo/CheckPwPage.js
  src/pages/modifyUserInfo/ModifyUserInfoPage.js
  src/pages/modifyUserInfo/ModifyUserInfoPage.scss
Labels: 🐛BUG, 💄UI/UX

#175 [bug]: 회원가입 컴포넌트 내 중복 정보에 대한 예외처리 코드 추가 (#174)
  src/pages/register/RegisterPage.js
Labels: 🐛BUG, 💄UI/UX

#178 [fix]: 네비게이션 컴포넌트 내 접속자 요소 제거 (#177)
  src/components/Navigation.js
Labels: 💄UI/UX, 🛠FIX
